version: "3"
services:
  app:
    image: nodeapp
    depends_on:
      - postgres
    ports:
      - "7007:7007"



  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword

