version : '3'

services:
  nodeapp:
    image: nodeapp
    ports:
      - '7007:7007'
    depends_on:
      - pg

  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - wordapp-db:/var/lib/postgresql/data


volumes:
  wordapp-db:
